fix: add dummy command to docker create for cached image
Error: 'no command specified' when creating container from agnos-rootfs:latest
Fix: Add /bin/true as dummy command since the image has no CMD/ENTRYPOINT

This should allow the cached image extraction to work properly.